### ISSUE TITLE
in FileUtils, check that we have the STORAGE permission before reading / writing

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/KnightWatch#4]
Android 6 allows you to toggle off the STORAGE permission, so check for it in FileUtils.

**Comment by Stealth2994** [comment]
Added it and it succesfully checks my phone, need you to check yours because mine doesnt yet run android 6

**Comment by ounsworth** [comment]
Brilliant, if I remove Camera permission and then try to use the Camera from inside the app, it asks for the permission. Good job. I'm closing this ticket.

![screenshot_20151226-134419](https://cloud.githubusercontent.com/assets/5394395/12007539/1800825a-abd7-11e5-85fa-69e7b3a5e4f8.png)

**Comment by ounsworth** [comment]
Connor, are you sure you meant to post your comment on this issue? You probably meant to post it in the issue relating to the camera.

**Comment by ounsworth** [comment]
Fixed.

Added permission checks for abiity to read/write USB storage. If you don't grant that permission then the app just asks repeatedly and is unusable, which is fine the abitily to save files there is core the the app being able to do anything.
